#!/bin/sh

VER_MAJOR_MINOR=`git describe --tags --abbrev=0|sed -e 's/[^0-9.]//g'`
VER_REV=`git rev-list --count HEAD`
VERSION=$VER_MAJOR_MINOR.$VER_REV

read COPYRIGHT < src/COPYRIGHT

# make bdf
bin/hex2bdf \
	--copyright="$COPYRIGHT" \
	--version="$VERSION" \
	build/ufo.hex > build/ufo.bdf

# make pcf
bdftopcf -t build/ufo.bdf > build/ufo.pcf

# make gryph map
bin/hex2png \
	build/ufo.hex ufo.png \
	--block=src/unicode/Blocks.txt
